BCP.Microservicio.Aplicacion/Controllers/TarjetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BCP.Sap.Models.Enviar;
using BCP.Framework.Common;
using BCP.Sap.Connectors;
using BCP.Framework.Logs;
using BCP.Sap.Models.Rebibir;
using BCP.Sap.Models.Enviar.Tarjeta;
using BCP.Sap.Models.Sap;
using BCP.Sap.Models.Rebibir.Tarjeta;
using BCP.Sap.Business;
using BCP.Sap.Models.Rebibir.SmartLink;
using BCP.Sap.Models.Configuracion;

namespace BCP.Microservicio.Aplicacion.Controllers
{
    public class TarjetaController : Controller
    {
        private readonly ISapBusiness _business;
        private readonly ILogger _logger;
        private string _operacion;
        public TarjetaController(ILogger logger, ISapBusiness business)
        {
            this._logger = logger;
            this._business = business;
        }

        #region VISTAS
        public ActionResult Bloqueo(string tarjeta)
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    BloqueoDBData consulta = new BloqueoDBData();

                    var json = ManagerJson.SerializarObjecto(ConsultaTarjeta(tarjeta, 0,null).Value);
                    RespuestaConsultaTarjeta resultadoConsulta = ManagerJson.DeserializarObjecto<RespuestaConsultaTarjeta>(json);
                    if (resultadoConsulta.success)
                    {
                        string[] situacion = new string[] { "06", "03", "11", "12" };
                        if (!situacion.Contains(resultadoConsulta.data.situacion))
                        {
                            return RedirectToAction("SelBloqueo");
                        }
                        consulta.codBloqueo = resultadoConsulta.data.codigoBloqueo;
                        consulta.tarjeta = resultadoConsulta.data.tarjeta;
                        consulta.fechaVenTarj = resultadoConsulta.data.fechaExpiracion;
                        consulta.idcDB = resultadoConsulta.data.idc;
                        consulta.tidcDB = resultadoConsulta.data.tipoIDC;
                        consulta.nombre = resultadoConsulta.data.nombreTarjeta;
                    }
                    return View(model: consulta);
                }
            }
        }
        public ActionResult Cambio()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (!sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_MAN_PER_COM_T") && sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_CAM_RAP_TAR"))
                {
                    limpiarFlujos();
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult CargaBloqueo()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    limpiarFlujos();
                    return View();
                }
            }
        }
        public ActionResult PinCosto()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    SeguimientoProcesos pasos = ManagerJson.DeserializarObjecto<SeguimientoProcesos>(HttpContext.Session.GetString("procesoApertura"));
                    string tarjeta = pasos.detalleCliente.First().tarjeta;
                    return View(model: (new string[] { "12", string.IsNullOrEmpty(tarjeta) ? string.Empty : tarjeta }));
                }
            }
        }
        public ActionResult Prod()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_TAR_PRO"))
                {
                    limpiarFlujos();
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult Stocks()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_STO")) 
                {
                    limpiarFlujos();
                    Stock data = new Stock();
                    data.sucursal = sesion.host.sucursal;
                    data.agencia = sesion.host.agencia;
                    return View(model: data);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult Tramite()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_PRO_TAR"))
                {
                    limpiarFlujos();
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult SelBloqueo()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (sesion.usuario.politicas.Split('|').Contains("SAPP_BO_TAR_COT_BLO_REG_BLO"))
                {
                    limpiarFlujos();

                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult Sat(bool consulta, bool tarjetaNueva, int indice, string tarjeta, string exclusiva)
        {
            Sesion sesion = new Sesion();
            int contadorSeguro = 0;
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                string[] menu = sesion.usuario.politicas.Split('|');
                if (menu.Contains("SAPP_BO_TAR") && menu.Contains("SAPP_BO_TAR_MAN"))
                {                    
                    ConsultaTarjeta resultado = new ConsultaTarjeta();
                    string proceso = "Sat";
                    string tipoPersona = "N";

BCP.Microservicio.Aplicacion/Views/Tarjeta/Bloqueo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using BCP.Sap.Models.Sap;
@using Microsoft.AspNetCore.Http;
@using BCP.Framework.Common;
@using BCP.Sap.Models.Enviar.Tarjeta;
@model BloqueoDBData;
@{
    Sesion sesion;
    string[] politicas = { };
    if (Context.Session.GetString("autorizado") == null)
    {
        sesion = new Sesion();
    }
    else
    {
        sesion = ManagerJson.DeserializarObjecto<Sesion>(Context.Session.GetString("autorizado"));
        politicas = sesion.usuario.politicas.Split('|');
    }
}
@{
    ViewData["Title"] = "Bloqueo: ";
}
<div class="container border border-primary" style="background-color:lightgrey">
    <header>
        <h4>Bloqueo:</h4>
    </header>
    <form id="BloqueoDB" name="BloqueoDB" method="post" action="#">
        <div class="container mb-1">
            <div class="form-row">
                <label asp-for="codBloqueo" class="col-sm-2 col-form-label">
                    Nro. Bloqueo:
                </label>
                <div class="col-sm-4">
                    <input readonly id="txtRBcodBloqueo" asp-for="codBloqueo" class="form-control" />
                </div>
                <label for="cbRBmotivo" class="col-sm-3 col-form-label">
                    Motivo de Bloqueo:
                </label>
                <div class="col-sm-3">
                    <select id="cbRBmotivo" class="form-control" name="motivo">
                        <option selected value="E">EXTRAVIO</option>
                        <option value="R">ROBO</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-10">
                <div class="container mb-1">
                    <fieldset class="border border-dark">
                        <legend class="w-auto" style="font-size:14px;">
                            Datos de Tarjeta
                        </legend>
                        <div class="container">
                            <div class="form-row">
                                <label asp-for="tarjeta" class="col-sm-3 col-form-label">
                                    Tarjeta nro:
                                </label>
                                <div class="col-sm-9">
                                    <input id="txtRBTarjeta" class="form-control" asp-for="tarjeta" readonly />
                                </div>
                            </div>
                            <div class="form-row">
                                <label asp-for="fechaVenTarj" class="col-sm-3 col-form-label">
                                    Fecha de Vencimiento:
                                </label>
                                <div class="col-sm-9">
                                    <input readonly id="txtRBfechaVenTarj" class="form-control" asp-for="fechaVenTarj"  />
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="container">
                    <fieldset class="border border-dark">
                        <legend class="w-auto" style="font-size:14px;">
                            Datos del Titular
                        </legend>
                        <div class="container">
                            <div class="form-row">
                                <label asp-for="idcDB" class="col-sm-3 col-form-label">
                                    IDC:
                                </label>
                                <div class="col-sm-7">
                                    <input id="txtRBIDC" class="form-control" asp-for="idcDB" readonly />
                                </div>
                                <div class="col-sm-1">
                                    <input id="txttRBIDC" class="form-control" asp-for="tidcDB" readonly/>
                                </div>
                            </div>
                            <div class="form-row">
                                <label asp-for="nombre" class="col-sm-3 col-form-label">
                                    Nombre:
                                </label>
                                <div class="col-sm-9">
                                    <input id="txtRBNombre" class="form-control" asp-for="nombre" readonly />
                                </div>
                            </div>
                            <div class="form-row">
                                <label for="txRBTelefono" class="col-sm-3 col-form-label">
                                    Teléfono:
                                </label>
                                <div class="col-sm-9">
                                    <input id="txRBTelefono" class="form-control" type="text" name="telefono" />
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="container mb-1">
                    <fieldset class="border border-dark">
                        <legend class="w-auto" style="font-size:14px;">
                            Del bloqueo
                        </legend>
                        <div class="container">
                            <div class="form-row">
                                <label for="txtRBNomReporta" class="col-sm-3 col-form-label">
                                    Nombre de quien reportó el bloqueo:
                                </label>
                                <div class="col-sm-9">
                                    <input id="txtRBNomReporta" class="form-control" type="text" name="nombreReporta" />
                                </div>
                            </div>
                            <div class="form-row">
                                <label for="txtRBObservaciones" class="col-sm-3 col-form-label">
                                    Observaciones:
                                </label>
                                <div class="col-sm-9">
                                    <textarea id="txtRBObservaciones" class="form-control" name="observaciones"></textarea>
                                </div>
                            </div>
                            <div class="form-row">
                                <label for="txtRBFechBloqueo" class="col-sm-3 col-form-label">
                                    Fecha y Hora de Bloqueo:
                                </label>
                                <div class="col-sm-9">
                                    <input id="txtRBFechBloqueo" class="form-control" type="text" value="@DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss")" readonly />
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="col h-100 w-100">
                    <div class="align-text-bottom w-100">
                        @if (politicas.Contains("SAPP_BO_TAR_COT_BLO_REG_BLO"))
                        {
                            <button type="submit" class="my-1 w-100 btn btn-outline-secondary">
                                <i class="fas fa-check icono-2x"></i><br>
                                Aceptar
                            </button><br>
                            <button class="my-1 w-100 btn btn-outline-secondary">
                                <i class="fas fa-edit icono-2x"></i><br>
                                Nuevo
                            </button><br>
                        }
                        else
                        {
                            <button class="my-1 w-100 btn btn-outline-secondary" disabled>
                                <i class="fas fa-check icono-2x"></i><br>
                                Aceptar
                            </button><br>
                            <button class="my-1 w-100 btn btn-outline-secondary" disabled>
                                <i class="fas fa-edit icono-2x"></i><br>
                                Nuevo
                            </button><br>

                        }
                        <button id="btRBloqueoCerrar" type="button" onclick="location.href='@Url.Action("Index","Home")'" class="my-1 w-100 btn btn-outline-secondary">
                            <i class="fas fa-window-close icono-2x"></i><br>
                            Cerrar
                        </button>
                    </div>
                        
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('#BloqueoDB').on('submit', function (e) {
        e.preventDefault();
        var parametros = $(this).serialize();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("RegistroBloqueoDB","Tarjeta")',
            dataType: 'json',
            data: parametros,
            beforeSend: AntesAjax(),
            success: function (l) {
                DespuesAjax();
                alert(l.message);
            },
            error: function (ex, textStatus, errorThrown) {
                DespuesAjax();
                AjaxErrorHandler(ex, textStatus, errorThrown);
            }
        });
    } );
</script>

BCP.Microservicio.Aplicacion/Views/Tarjeta/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

BCP.Microservicio.Aplicacion/Views/Tarjeta/PinCosto.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model string[];
@{
    ViewData["Title"] = "Cambio de Tarjeta Paso 5 - Tarjeta Credimas: ";
    int tamanio = int.Parse(Model[0]);
    string PCTarjeta = string.Empty;
    if (!string.IsNullOrEmpty(Model[1]))
    {
        PCTarjeta = Model[1];
    }
    if(tamanio==11)
    {
        tamanio = tamanio - 1;
    }
}
<div class="container border border-primary" style="background-color:lightgrey">
    <form id="PCSubmit" name="PCSubmit" method="post" action="#">
        @if (tamanio == 12)
        {
            <header id="PCFlujo">
                <h4>Cambio de Tarjeta Paso 5 - Tarjeta Credimas:</h4>
            </header>
        }
        <input id="hPinCostoTarjeta" type="hidden" value="@PCTarjeta" name="tarjeta" />
        <div class="form-row">
            <div class="col-sm-@tamanio mb-1">
                <div class="container">
                    <fieldset class="border border-dark">
                        <legend class="w-auto" style="font-size:14px;">
                            De la opción de bloqueo
                        </legend>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group form-check">
                                        <input id="rbcPIN" value="false" name="cobro" class="form-check-input" type="radio" />
                                        <label for="rbcPIN" class="form-check-label">
                                            Con Pin
                                        </label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input id="rbsPIN" value="true" name="cobro" class="form-check-input" type="radio" checked />
                                        <label for="rbsPIN" class="form-check-label">
                                            Sin Pin
                                        </label>
                                    </div>
                                </div>
                                <div class="col-sm-6 mb-1">
                                    <fieldset class="border border-dark">
                                        <legend class="w-auto" style="font-size:13px;">
                                            Valor del PIN
                                        </legend>
                                        <div class="container">
                                            <input id="hPin" type="hidden" value="" name="pinEncriptado" />
                                            <input id="txtvPIN" class="form-control" type="password" readonly />
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            @if (tamanio == 10)
            {
                <input id="hPPPin" type="hidden" value="" />
                <div class="col-sm-2">
                    <div class="row m-0 p-0">
                        <button type="button" class="col col-sm-12 btn btn-outline-secondary m-1" onclick="bloqueo(document.getElementById('rbcPIN').checked)">
                            <i class="fas fa-check icono-2x"></i><br />Aceptar
                        </button>
                        <button type="button" class="col col-sm-12 btn btn-outline-secondary m-1" onclick="$('#PinCModal').modal('hide');">
                            <i class="fas fa-window-close icono-2x"></i><br />Cancelar
                        </button>
                    </div>
                </div>
            }
            else
            {
                <div class="col-sm-12">
                    <div class="container mb-1">
                        <fieldset class="border border-dark">
                            <legend class="w-auto" style="font-size:14px;">
                                De la Nueva Tarjeta
                            </legend>
                            <div class="container">
                                <div class="form-row">
                                    <label for="txtnTarjeta" class="col-sm-3 col-form-label">
                                        Número de Tarjeta:
                                    </label>
                                    <div class="col-sm-9">
                                        <input id="txtnTarjeta" name="tarjetaNueva" value="" class="form-control" type="text"  placeholder="0000-0000-0000-0000" maxlength="19" autofocus required />
                                    </div>
                                </div>
                                <div class="container mt-1 mb-1" style="display:none;">
                                    <fieldset class="border border-dark p-2">
                                        <legend class="w-auto" style="font-size:13px;">
                                            Ingrese los motivos de la Reposición sin costo
                                        </legend>
                                        <div class="container">
                                            <input id="txtMotRenov" class="form-control" type="text" />
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="d-inline p-1">
                        <footer>
                            <div class="form-row justify-content-center align-items-center">
                                <div class="col-auto m-1">
                                    <button type="button" class="btn border btn-light" onclick="window.history.back()">&lt;&lt;Anterior&lt;&lt;</button>
                                </div>
                                <div class="col-auto m-1">
                                    <button type="button" class="btn border btn-light" onclick="cancelarProceso('@Url.Action("Index","Home")');">Cancelar</button>
                                </div>
                                <div class="col-auto m-1">
                                    <input type="submit" class="btn border btn-light" value=">>Siguiente>>" />
                                </div>
                            </div>
                        </footer>
                    </div>
                </div>
            }
        </div>
    </form>
</div>
<script type="text/javascript">
    $("#txtvPIN").keydown(function (e) {
        var keyCode = e.keyCode || e.which;
        if(keyCode === 8){
            e.preventDefault();
            $("#hPin").val("");
            $("#txtvPIN").val("");
        }
        else if (keyCode === 123) {
            e.preventDefault();
            document.getElementById('rbsPIN').checked = true;
            var tarjeta = $("#hPinCostoTarjeta").val().replace(/-/g, "").replace(/ /g, "");
            if (tarjeta != "") {
                var url = 'http://localhost:9991/Values/GetPin/' + tarjeta;
                $.ajax({
                    type: 'GET',
                    url: url,
                    cache: false,
                    dataType: 'text',
                    beforeSend: function () {
	                    $("#lbCargandoElementoModal").html("El Cliente debe digitar su Clave...");
	                    AntesAjax();
                    },
                    success: function (l) {
                        if (l == null || l == "") {
                            alert("NO SE PUDO COMUNICAR CON EL PIN PAD");
                        }
                        else {
                            var resultado = l.replace(/"/g, "").split(',');
                            if (resultado[1] == null || resultado[1] == "") {
                                alert("NO SE PUDO COMUNICAR CON EL PIN PAD");
                            }
                            else if (resultado[0] == "00") {
                                $("#hPin").val(resultado[1]);
                                $("#txtvPIN").val("1234");
                                document.getElementById('rbcPIN').checked = true;
                            }
                            else {
                                alert("DATOS DEL PIN NO RECUPERADOS, INTENTE NUEVAMENTE");
                                $("#hPin").val("");
                                $("#txtvPIN").val("ÔÕÖ×");
                            }
                        }
                    },
                    error: function (ex, textStatus, errorThrown) {
                        AjaxErrorHandler(ex, textStatus, errorThrown);
                    },
                    complete: function () {
                        DespuesAjax();
                        $("#lbCargandoElementoModal").html("Cargando...");
                    }
                });
            }
            else {
                alert("DEBE INGRESAR LA TARJETA PRIMERO");
            }
        }
    });
    $("#txtnTarjeta").keyup(function (e) {
        var key=e.keyCode;
        $(this).val(formatoInputTarjeta($(this).val(),key));  
    });
    $('#PCSubmit').on('submit', function (e) {
        e.preventDefault();
        var siguiente = false;
        var parametros = $(this).serialize();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("CambioTarjeta","Tarjeta")',
            dataType: 'json',
            data: parametros,
            beforeSend: AntesAjax(),
            success: function (l) {
                DespuesAjax();
                if(l.message!='OK'){
                    alert(l.message);
                }
                siguiente = l.success;
            },
            error: function (ex, textStatus, errorThrown) {
                DespuesAjax();
                AjaxErrorHandler(ex, textStatus, errorThrown);
            },
            complete: function () {
                if (siguiente) {
                    location.href = '@Url.Action("ImpContrato","Home")';
                }
            }
        });
    });
</script>