BCP.Microservicio.Aplicacion/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using BCP.Sap.Connectors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BCP.Sap.Models.Enviar;
using BCP.Framework.Common;
using BCP.Sap.Models.Rebibir;
using BCP.Framework.Logs;
using BCP.Sap.Models.Enviar.Tarjeta;
using BCP.Sap.Models.Sap;
using BCP.Sap.Models.Rebibir.Tarjeta;
using BCP.Sap.Business;
using BCP.Sap.Models.Enviar.ProcesoApertura;
using System.Linq;

namespace BCP.Microservicio.Aplicacion.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly ILogger _logger;
        private readonly ISapBusiness _business;
        private string _operacion;
        public ConsultaController(ILogger logger, ISapBusiness business)
        {
            this._logger = logger;
            this._business = business;
        }

        #region TARJETA        
        public ActionResult EntregaTarjeta()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    string[] menu = sesion.usuario.politicas.Split('|');
                    if (!menu.Contains("SAPP_BO_TAR_MAN_PER_COM_T") && menu.Contains("SAPP_BO_TAR") && menu.Contains("SAPP_BO_TAR_ENT_ELI"))
                    {
                        string nombreProceso = "Entrega de Tarjeta";
                        SeguimientoProcesos pasos = new SeguimientoProcesos
                        {
                            nombreProceso = nombreProceso,
                            detalleCliente = new List<DatosCliente>(),                            
                        };
                        pasos.detalleCliente.Add(new DatosCliente { detalleCuenta = new List<AperturaCuenta>() });
                        HttpContext.Session.SetString("procesoApertura", ManagerJson.SerializarObjecto(pasos));
                        return RedirectToAction("AlfabeticaTarjeta");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }            
        }
        public ActionResult AlfabeticaTarjeta()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    string usoPagina = "";
                    if (HttpContext.Session.GetString("procesoApertura") != null)
                    {
                        SeguimientoProcesos pasos = ManagerJson.DeserializarObjecto<SeguimientoProcesos>(HttpContext.Session.GetString("procesoApertura"));
                        if (pasos.detalleCliente.Count > 0)
                        {
                            int indice = 0;
                            if (pasos.nombreProceso.Equals("Apertura"))
                            {
                                try
                                {
                                    indice = int.Parse(Request.Form["indice"].ToString());
                                }
                                catch (Exception ex) { }
                            }
                            string nombre = "";
                            if (!(pasos.nombreProceso.Equals("Entrega de Tarjeta") || pasos.nombreProceso.Equals("ConsultaTarjeta")))
                            {
                                if (pasos.tipoPersona.Equals("J"))
                                {
                                    nombre = pasos.detalleCliente[indice].pj.razonSocial;
                                }
                                else
                                {
                                    nombre = pasos.detalleCliente[indice].pn.paterno + " " + pasos.detalleCliente[indice].pn.materno + " " + pasos.detalleCliente[indice].pn.nombres;
                                }
                            }
                            TempData["nombre"] = indice.ToString() + "-" + nombre;
                            usoPagina = "Proceso" + pasos.nombreProceso;
                        }
                        else
                        {
                            usoPagina = pasos.nombreProceso;
                        }
                    }
                    else
                    {
                        limpiarFlujos();
                        usoPagina = "ConsultaTarjeta";
                        SeguimientoProcesos pasos = new SeguimientoProcesos
                        {
                            nombreProceso = usoPagina,
                            detalleCliente = new List<DatosCliente>()
                        };
                        pasos.detalleCliente.Add(new DatosCliente { detalleCuenta = new List<AperturaCuenta>() });
                        HttpContext.Session.SetString("procesoApertura", ManagerJson.SerializarObjecto(pasos));
                    }
                    TempData["usoPagina"] = usoPagina;
                    return View();
                }
            }           
        }

        [HttpPost]
        public JsonResult CAT(string nombre)
        {
            RespuestaBusquedaTarjeta response = new RespuestaBusquedaTarjeta();
            this._operacion = ManagerOperation.GenerateOperation();
            try
            {
                Sesion sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                response = this._business.BusquedaTarjeta(sesion, nombre);
            }
            catch (Exception ex)
            {
                Logger.Error("[{0}] ->    ERROR: {1} , Exception: {2}", this._operacion, ex.Message, ManagerJson.SerializarObjecto(ex));
            }
            finally
            {
                Logger.Debug("[{0}] -> RESPONSE: {1}", this._operacion, ManagerJson.SerializarObjecto(response));
            }
            return Json(response);
        }
        #endregion

        #region ALS 
        public ActionResult AlfabeticaClienteALS()
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else if (sesion.usuario.politicas.Split('|').Contains("SAPP_BO_CON_ALS"))
                {
                    limpiarFlujos();
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult InfoProductoALS(AlsInformeCrediticioRequest credito)
        {
            Sesion sesion = new Sesion();
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                sesion = ManagerJson.DeserializarObjecto<Sesion>(HttpContext.Session.GetString("autorizado"));
                if (!sesion.autorizado)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    limpiarFlujos();
                    AlsInformeCrediticioItem data = new AlsInformeCrediticioItem();
                    if (credito != null)
                    {
                        if (credito.codigoCredito != null)
                        {
                            if (!credito.codigoCredito.Equals(""))
                            {
                                var json = ManagerJson.SerializarObjecto(ConsultaInformeCrediticioALS(credito).Value);
                                RecibirALSInformeCrediticio respuesta = ManagerJson.DeserializarObjecto<RecibirALSInformeCrediticio>(json);
                                if (respuesta != null)
                                {
                                    if (respuesta.success)
                                    {
                                        if (respuesta.data.total > 0)
                                        {
                                            if (credito.item < respuesta.data.total)
                                                data = respuesta.data.rows[0];
                                            data.nombres = credito.nombre;
                                            return View(model: data);
                                        }
                                    }
                                }

                            }
                        }
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        public ActionResult ProductoClienteALS(string customer)
        {
            if (HttpContext.Session.GetString("autorizado") == null)
            {
                return RedirectToAction("Index", "Home");
            }

BCP.Microservicio.Aplicacion/Views/Consulta/AlfabeticaCliente.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using BCP.Sap.Models.Sap;
@using Microsoft.AspNetCore.Http;
@using BCP.Framework.Common; 
@{
    Sesion sesion;
    string[] politicas = { };
    if (Context.Session.GetString("autorizado") == null)
    {
        sesion = new Sesion();
    }
    else
    {
        sesion =ManagerJson.DeserializarObjecto<Sesion>(Context.Session.GetString("autorizado"));
        politicas = sesion.usuario.politicas.Split('|');
    }
}
@{
    ViewData["Title"] = "Consulta Alafabética de Clientes: ";
}
<div class="container border border-primary" style="background-color:lightgrey">
    <header>
        <h4>Consulta Alfabética de Clientes:</h4>
    </header>
    <div class="form-row">
        <div class="col-lg-10 mb-3">
            <div class="form-row">
                <label for="txtApRS" class="col-sm-4 col-form-label">
                    Apellido Paterno o Razón Social:
                </label>
                <div class="col-sm-8">
                    <input id="txtApRS" class="form-control" type="text" value="" autofocus />
                </div>
            </div>
            <div class="form-row">
                <label for="txtAM" class="col-sm-4 col-form-label">
                    Apellido Materno:
                </label>
                <div class="col-sm-8">
                    <input id="txtAM" value="" class="form-control" type="text" />
                </div>
            </div>
            <div class="form-row">
                <label for="txtNom" class="col-sm-4 col-form-label">
                    Nombres:
                </label>
                <div class="col-sm-8">
                    <input id="txtNom" value="" class="form-control" type="text" />
                </div>
            </div>
        </div>
        <div class="col-lg-10" id="divtb" style="display:none;">
            <div class="table-responsive bg-white" style="max-height:300px;">
                <table id="tbCAC" class="table table-bordered table-striped">
                    <thead class="thead-light">
                        <tr>
                            <th>Documento</th>
                            <th>Tipo</th>
                            <th>&nbsp;</th>
                            <th>Nombres</th>
                            <th>T. Cliente</th>
                            <th>T. Banca</th>
                            <th>Oficina</th>
                            <th>Fun. Negocios</th>
                            <th>Fecha de Nacimiento</th>
                        </tr>
                    </thead>
                    <tbody> </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-2">
            <center>
                @if (politicas.Contains("SAPP_BO_CLI_CON_ALF"))
                {
                    <button id="btCA" class="my-1 w-100 btn btn-outline-secondary">
                        <i class="fas fa-print icono-2x"></i><br />Consultar
                    </button>
                }
                else
                {
                    <button id="btCA" class="my-1 w-100 btn btn-outline-secondary" disabled>
                        <i class="fas fa-print icono-2x"></i><br />Consultar
                    </button>
                }
                <button id="btCACSiguiente" class="my-1 w-100 btn btn-outline-secondary" style="display:none;">
                    <i class="fas fa-arrow-down icono-2x"></i><br />Siguiente
                </button>
                <button id="btCAAceptar" class="my-1 w-100 btn btn-outline-secondary" style="display:none;">
                    <i class="fas fa-check icono-2x"></i><br />Aceptar
                </button>
                <button id="btCACerrar" onclick="location.href='@Url.Action("Index","Home")'" class="my-1 w-100 btn btn-outline-secondary">
                    <i class="fas fa-window-close icono-2x"></i><br />Cerrar
                </button>
            </center>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#btCA").click(function () {
        $("#tbCAC tbody").empty();
        $("#divtb").hide();
        $("#btCACSiguiente").hide();
        var nombres = $("#txtApRS").val();
        if (nombres == "" || nombres == " ") {
            alert("Debe ingresar el apellido paterno o razon social");

        }
        else {
            if (!($("#txtAM").val()== "" || $("#txtAM").val() == " ")) {
                nombres = nombres + "|" + $("#txtAM").val();
            }
            if (!($("#txtNom").val() == "" || $("#txtNom").val() == " ")) {
                nombres = nombres + "|" + $("#txtNom").val();
            }
            CAC(nombres,false,"","","");
        }
    });
    function CAC(nombres,completo,idc, idt,ide) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("ConsultaAlfabetica","Consulta")',
            dataType: 'json',
            data: { cliente: nombres, completo: completo, idc: idc, idt:idt, ide:ide },
            beforeSend: AntesAjax(),
            success: function (l) {
                if (l.state == null) {
                    alert("error de conexion al microservicio");
                }
                else {
                    if (l.success) {
                        var nfila = ($("#tbCAC tr").length) - 1;
                        if (l.data.length > 0) {
                            for (var i = 0; i < l.data.length; i++) {
                                if (i > 0 || completo == false) {
                                    nfila = nfila + 1;
                                    var fia = '<tr id="' + (nfila) + '">' +
                                        '<td id="xidc' + (nfila) + '">' + l.data[i].idcNumero + '</td>' +
                                        '<td id="xidt' + (nfila) + '">' + l.data[i].idcTipo + '</td>' +
                                        '<td id="xide' + (nfila) + '">' + l.data[i].idcExtension + '</td>' +
                                        '<td id="xnom' + (nfila) + '">' + l.data[i].nombreCompleto + '</td>' +
                                        '<td>' + l.data[i].tipoCliente + '</td>' +
                                        '<td>' + l.data[i].tipoBanca + '</td>' +
                                        '<td>' + l.data[i].oficina + '</td>' +
                                        '<td>' + l.data[i].codigo + '</td>' +
                                        '<td>' + l.data[i].fechaNacimiento + '</td>' +
                                        '</tr>';
                                    $("#tbCAC tbody").append(fia);
                                    if (nfila == 1) {
                                        $("#divtb").show();
                                        $("#btCACSiguiente").show();
                                        $("#tbCAC #1").addClass("bg-info");
                                    }
                                }
                            }
                        }
                        else {
                            $("#btCACSiguiente").hide();
                            alert("NO SE ENCONTRARON MAS COINCIDENCIAS");
                        }
                    }
                    else {
                        alert("Error de consulta al microservicio");
                    }
                }
            },
            error: function (ex, textStatus, errorThrown) {
                AjaxErrorHandler(ex, textStatus, errorThrown);
            },
            complete: function () { DespuesAjax(); }
        });
    }
    $('#tbCAC').on('click', 'tbody tr', function () {
        var selected=$(this).hasClass("bg-info");
        if(!selected){
            $("#tbCAC tbody tr").removeClass("bg-info");
            $(this).addClass("bg-info");        
        } 
    });
    $('#btCACSiguiente').click( function () {
        var nfila = ($("#tbCAC tr").length) - 1;
        var pn = [ "P", "Q", "S", "Y" ];
        var idt = $("#xidt" + (nfila) + "").html();
        var nombres = $("#xnom" + (nfila) + "").html();
        if (!(pn.indexOf(idt) === -1)) {
            nombres=nombres.replace(' ', '|');
            nombres=nombres.replace(' ', '|');
        }
        CAC(nombres, true, $("#xidc" + (nfila) + "").html(), idt, $("#xide" + (nfila) + "").html());
        /*for (var i = 1; i <= nfila; i++) {
            if ($("#tbCAC #" + i + "").hasClass("bg-info")) {
                $("#tbCAC #" + i + "").removeClass("bg-info");
                $("#tbCAC #" + ((i % nfila) + 1) + "").addClass("bg-info")
                break;
            }
        }*/
    })
</script>

BCP.Microservicio.Aplicacion/Views/Consulta/AlfabeticaClienteALS.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using BCP.Sap.Models.Sap;
@using Microsoft.AspNetCore.Http;
@using BCP.Framework.Common;
@{
    Sesion sesion;
    string[] politicas = { };
    if (Context.Session.GetString("autorizado") == null)
    {
        sesion = new Sesion();
    }
    else
    {
        sesion = ManagerJson.DeserializarObjecto<Sesion>(Context.Session.GetString("autorizado"));
        politicas = sesion.usuario.politicas.Split('|');
    }
}
@{
    ViewData["Title"] = "ALS-Consulta Alafabética de Clientes: ";
}
<div class="container border border-primary" style="background-color:lightgrey">
    <header>
        <h4>ALS-Consulta Alafabética de Clientes:</h4>
    </header>
    <div class="container mb-3">
        <div class="row">
            <div class="col-sm-9">
                <div class="form-row">
                    <label for="txtApRS" class="col-sm-4 col-form-label">
                        Apellido Paterno o Razón Social:
                    </label>
                    <div class="col-sm-8">
                        <input id="txtApRS" class="form-control" type="text" autofocus />
                    </div>
                </div>
                <div class="form-row">
                    <label for="txtAM" class="col-sm-4 col-form-label">
                        Apellido Materno:
                    </label>
                    <div class="col-sm-8">
                        <input id="txtAM" class="form-control" type="text" />
                    </div>
                </div>
                <div class="form-row">
                    <label for="txtNom" class="col-sm-4 col-form-label">
                        Nombres:
                    </label>
                    <div class="col-sm-8">
                        <input id="txtNom" class="form-control" type="text" />
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <fieldset class="border border-dark">
                    <legend class="w-auto" style="font-size:14px;">
                        Tipo de Búsqueda
                    </legend>
                    <div class="container">
                        <div class="form-check form-check-inline">
                            <input id="rbNormal" value="N" class="form-check-input" name="tBusqueda" type="radio" />
                            <label for="rbNormal" class="form-check-label">
                                Normal
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input id="rbEspecial" value="E" class="form-check-input" name="tBusqueda" type="radio" checked />
                            <label for="rbEspecial" class="form-check-label">
                                Especial
                            </label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="container mb-3">
        <div class="form-row">
            <div class="col-lg-11">
                <div class="table-responsive bg-white" style="max-height:300px;">
                    <table id="tbALSCA" class="table table-bordered table-striped">
                        <thead class="thead-light">
                            <tr>
                                <th>Nombre</th>
                                <th>Dirección</th>
                                <th>Customer</th>
                                <th>Fecha de Nacimiento</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="col-lg-1">
                <form id="ALSCA" name="fALSCA" method="post" action="@Url.Action("ProductoClienteALS")">
                    <input type="hidden" name="customer" id="hCustomer" value="" />
                    <center>
                        @if (politicas.Contains("SAPP_BO_CON_ALS"))
                        {
                            <button type="button" id="btConsulta" class="my-1 w-100 btn btn-outline-secondary">
                                <i class="fas fa-print icono-2x"></i><br />Consultar
                            </button>
                        }
                        else
                        {
                            <button type="button" class="my-1 w-100 btn btn-outline-secondary" disabled>
                                <i class="fas fa-print icono-2x"></i><br />Consultar
                            </button>
                        }
                        <button id="btAnterior" onclick="cambiarSeleccion(0,-1)" type="button" class="my-1 w-100 btn btn-outline-secondary" disabled>
                            <i class="fas fa-arrow-up icono-2x"></i><br />Anterior
                        </button>
                        <button id="btSiguiente" onclick="cambiarSeleccion(0,1)" type="button" class="my-1 w-100 btn btn-outline-secondary" disabled>
                            <i class="fas fa-arrow-down icono-2x"></i><br />Siguiente
                        </button>
                        <button type="submit" id="btProductos" class="my-1 w-100 btn btn-outline-secondary" disabled>
                            <i class="fas fa-keyboard icono-2x"></i><br />Productos
                        </button>
                        <button type="button" onclick="location.href='@Url.Action("Index","Home")'" class="my-1 w-100 btn btn-outline-secondary">
                            <i class="fas fa-window-close icono-2x"></i><br />Cerrar
                        </button>
                    </center>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#btConsulta").click(function () {
        if ($("#txtApRS").val() != "") {
            var parametros = {
                datos: {
                    paterno: $("#txtApRS").val(),
                    materno: $("#txtAM").val(),
                    nombres: $("#txtNom").val(),
                    tipoConsulta: $('input[type="radio"][name="tBusqueda"]:checked').val()
                }
            };
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ConsultaAlfabeticaALS", "Consulta")',
                data: parametros,
                beforeSend: AntesAjax(),
                dataType: 'json',
                success: function (l) {
                    DespuesAjax();
                    if (l == null) {
                        alert("Error de conexion al microservicio");
                    }
                    else if (l.state == null) {
                        alert('Error de procesamiento de la consulta');
                    }
                    else if (!l.success) {
                        alert("Producto no encontrado");
                    }
                    else {
                        $("#tbALSCA tbody").empty();
                        $("#btSiguiente").prop('disabled', true);
                        $("#btAnterior").prop('disabled', true);
                        $("#btProductos").prop('disabled', true);
                        $("#hCustomer").val("");
                        for (var i = 0; i < l.data.total; i++) {
                            var fia = '<tr id="' + (i + 1) + '">' +
                                '<td>' + l.data.rows[i].nombre + '</td>' +
                                '<td>' + l.data.rows[i].direccion + '</td>' +
                                '<td id="tdC'+(i+1)+'">' + l.data.rows[i].customer + '</td>' +
                                '<td>' + l.data.rows[i].fechaNacimiento + '</td>' +
                                '</tr>';
                            $("#tbALSCA tbody").append(fia);
                        }
                        if (l.data.total > 1) {
                            $("#tbALSCA #1").addClass("bg-info");
                            $("#hCustomer").val($("#tdC1").html());
                            $("#btSiguiente").prop('disabled', false);
                            $("#btProductos").prop('disabled', false);
                        }
                    }
                },
                error: function (ex, textStatus, errorThrown) {
                    AjaxErrorHandler(ex, textStatus, errorThrown);
                },
            });
        }
        else {
            alert("Debe ingresar nombre o razon social");
        }
    });
    $('#tbALSCA').on('click', 'td', function () {
        var id = $(this).parents('tr').attr('id');
        cambiarSeleccion(id, 0);
    });
    $('#ALSCA').on('submit', function (e) {
        if ($("#hCustomer").val()=="") {
            e.preventDefault();
            alert("No se selecciono productos");
        }
    });
    function cambiarSeleccion(id,incremento) {
        var nfila = ($("#tbALSCA tr").length) - 1;
        if (nfila > 1) {
            for (var i = 1; i <= nfila; i++) {
                if ($("#tbALSCA #" + i + "").hasClass("bg-info")) {
                    $("#tbALSCA #" + i + "").removeClass("bg-info");
                    if (id == 0) {
                        id = (i+(1 * incremento));
                    }
                    break;
                }
            }
            $("#tbALSCA #" + id + "").addClass("bg-info");
            $("#hCustomer").val($("#tdC" + id + "").html());
            if (id == 1) {
                $("#btAnterior").prop('disabled', true);
            }
            else if (id == nfila) {
                $("#btSiguiente").prop('disabled', true);
            }
            else {
                $("#btAnterior").prop('disabled', false);
                $("#btSiguiente").prop('disabled', false);
            }
        }
    }
</script>